const ZERO = 0;
const ONE = 1;
const FOUR = 4;
const NINE = 9;
const START_INCLUSIVE = 0;
const END_INCLUSIVE = 9;
const MIN_TRIAL_NUMBER = 1;
const MIN_CARS_LENGTH = 2;
const MAX_CAR_LENGTH = 5;

export { ZERO, ONE, FOUR, NINE, START_INCLUSIVE, END_INCLUSIVE, MIN_TRIAL_NUMBER, MIN_CARS_LENGTH, MAX_CAR_LENGTH };
