const START_INCLUSIVE = 1;
const END_INCLUSIVE = 5;
const MAX_COACHES = 5;
const MIN_COACHES = 2;
const MIN_COACH_NAME = 2;
const MAX_COACH_NAME = 4;
const MIN_EXCLUDING_MENUS = 0;
const MAX_EXCLUDING_MENUS = 2;
const MAX_WEEKLY_CATEGORIES = 2;
const ZERO = 0;
const ONE = 1;

export { START_INCLUSIVE, END_INCLUSIVE, MAX_COACHES, MIN_COACHES, MIN_COACH_NAME, MAX_COACH_NAME, MIN_EXCLUDING_MENUS, MAX_EXCLUDING_MENUS, MAX_WEEKLY_CATEGORIES, ZERO, ONE }
