const START_INCLUSIVE = 1;
const END_INCLUSIVE = 45;
const LOTTO_NUMBER_COUNT = 6;
const PRICE_UNIT = 1000;
const HUNDRED = 100;
const TEN = 10;
const ZERO = 0;
const ONE = 1;
const THREE = 3;
const FOUR = 4;
const FIVE = 5;
const SIX = 6;
const THREE_PRIZE = 5000;
const FOUR_PRIZE = 50000;
const FIVE_PRIZE = 1500000;
const FIVE_PLUS_BONUS_PRIZE = 30000000;
const SIX_PRIZE = 2000000000;

export { START_INCLUSIVE, END_INCLUSIVE, LOTTO_NUMBER_COUNT, PRICE_UNIT, HUNDRED, TEN, ZERO, ONE, THREE, FOUR, FIVE, SIX, THREE_PRIZE, FIVE_PLUS_BONUS_PRIZE, FOUR_PRIZE, FIVE_PRIZE, SIX_PRIZE };
