const START_INCLUSIVE = 1;
const END_INCLUSIVE = 45;
const LOTTO_COUNT = 6;
const PRICE_UNIT = 1000;
const ZERO = 0;
const ONE = 1;

export { START_INCLUSIVE, END_INCLUSIVE, LOTTO_COUNT, PRICE_UNIT, ZERO, ONE };
