const ZERO = 0;
const ONE = 1;
const START_DATE = 1;
const END_DATE = 31;
const CHRISTMAS_DATE = 25;
const ADD_PRICE = 100;
const CHRISTMAS_DDAY_PRICE = 1000;
const MIN_EVENT_PRICE = 10000;
const MIN_FREE_PRICE = 120000;
const WEEK_PRICE = 2023;
const SPECIAL_PRICE = 1000;
const MIN_SANTA_PRICE = 20000;
const MIN_TREE_PRICE = 10000;
const MIN_STAR_PRICE = 5000;
const MAX_ORDER_QUANTITY = 20;

export { ZERO, ONE, START_DATE, END_DATE, CHRISTMAS_DATE, ADD_PRICE, CHRISTMAS_DDAY_PRICE, MIN_EVENT_PRICE, MAX_ORDER_QUANTITY, MIN_FREE_PRICE, WEEK_PRICE, SPECIAL_PRICE, MIN_STAR_PRICE, MIN_TREE_PRICE, MIN_SANTA_PRICE };
